### ISSUE TITLE
lower portion of index file deleted

### ISSUE THREAD

**Issue by jbphet** [phetsims/phetmarks#10]
Looks like something when wrong in commit https://github.com/phetsims/phetmarks/commit/fa068b6afb1d4d66b5c980f7c59dadd767b2bbd6, and the bottom portion of the index file got blown away.

**Comment by pixelzoom** [comment]
Hmmm... Looks like `cat index.html | grep -v fuzz100 > index.html` went wrong.

**Comment by pixelzoom** [comment]
Fixed in above commit. Also fixed incorrect (outdated) usages of `fuzzMouse` in the 'chipper' row.

@jbphet please verify.

**Comment by jbphet** [comment]
Looks good to me.  Closing.

**Comment by pixelzoom** [comment]
> I think it's generally unsafe to pipe back to the input file?

Indeed, I just didn't notice that I did that at the time.
