### ISSUE TITLE
Clean up js/phetmarks.js

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetmarks#11]
It was written as a prototype, and should be cleaned up and documented.

**Comment by jonathanolson** [comment]
Did a lot of cleanup, and fully reorganized the view.

Separated things into some class-like objects (repository/mode/screen/queryParameter selectors) which expose DOM element(s) and functions to get their current values.

I'm not really sure what standard to hold it up to. Maybe using require.js to grab phet-core (inherit!) and actually making them typed objects would be an improvement, if it doesn't increase the load time drastically.

I've added this to the list of things that gets linted, so it's passing that (missed 1 semicolon, 2 unused variables and was overwriting an unused param https://github.com/phetsims/phetmarks/commit/9f8fa1bcf7549965b11ba51bbc7bf1d84fd2d711).

@samreid, would you be willing to review and see how things should be improved?

**Comment by zepumph** [comment]
I don't know if this is the best place for this, but I found a bug while using the new phetmarks. Given this launch: 
![image](https://cloud.githubusercontent.com/assets/6856943/20506038/5ed6f77c-b00e-11e6-924e-03686acd6018.png)

I got this url:
http://localhost:8080/phet-io/wrappers/lab-book/lab-book.html?sim=beers-law-lab?ea

With two '?'

**Comment by jonathanolson** [comment]
@zepumph, I believe I fixed that bug in the above commit.

**Comment by samreid** [comment]
I haven't looked at the code yet, but had two recommendations:

1) Make the sim scrolling list smaller (such as 600px tall) or make it autoscroll so the selected item is visible. Often I will open it and it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/20977569/3e604744-bc63-11e6-9619-f00f039752c0.png)

So that I cannot see what sim is selected.

2) The PhET-iO wrappers should automatically override the ?brand=phet-io

**Comment by jonathanolson** [comment]
> Make the sim scrolling list smaller (such as 600px tall) or make it autoscroll so the selected item is visible. Often I will open it and it looks like this:

Bleh, it's supposed to auto-scroll. I can look into it.

> The PhET-iO wrappers should automatically override the ?brand=phet-io

Or we could just not have the brand=phet query parameter checkbox included in those?

**Comment by samreid** [comment]
> Or we could just not have the brand=phet query parameter checkbox included in those?

Excellent, thanks!

**Comment by samreid** [comment]
> Bleh, it's supposed to auto-scroll. I can look into it.

Reassigned to @jonathanolson for a bit.

**Comment by samreid** [comment]
On second thought, I'll keep this as a review issue and open a separate one for the auto-scroll.

**Comment by samreid** [comment]
Generally, it is looking very nice and a significant improvement over previous static phetmarks.  Some parts are a bit difficult for me to read.  I'm not sure if it would help more to add documentation or split it up differently:

```js
      get value() {
        var screensValue = screenSelector.value;
        return _.map( _.filter( $( toggleContainer ).find( ':checkbox' ), function( checkbox ) {
          return checkbox.checked;
        } ), function( checkbox ) {
          return checkbox.name;
        } ).concat( customTextBox.value.length ? [ customTextBox.value ] : [] ).concat(
          screensValue === 'all' ? [] : [ 'screens=' + screensValue ]
        ).join( '&' );
      },
```

I'm also wondering if it is necessary/preferable to populate the `modeData` object on startup, or change things to dynamically get the modes for each repository as it is selected (if that would be simpler).

A few methods have unused parameters.  If this is "we don't use it now but we may use it in the future", then it should be documented as such.  If not, the unused parameter should be removed.

I'm seeing `'testmarks-query-'` duplicated 3 times.  17 matches for `testmarks-`.  How about a phetmarks getItem() and setItem() method that automatically prepends this, or factoring it out into a constant?  Are you worried about refactoring in phetmarks leading to stale/buggy localstorage?  If so, we could prefix the key with a protocol/version string.

`createRepositorySelector` should take a list of repos as the argument, not the mode data.

Here's another method that could use more implementation line comments to help the reader understand what is happening:

```js
      reset: function() {
        screenSelector.reset();

        customTextBox.value = '';
        localStorage.setItem( 'testmarks-customText', '' );
        _.forEach( $( toggleContainer ).find( ':checkbox' ), function( checkbox ) {
          var parameter = _.filter( modeSelector.mode.queryParameters, function( param ) { return param.value === checkbox.name; } )[ 0 ];
          checkbox.checked = !!parameter.default;
          localStorage.setItem( 'testmarks-query-' + parameter.value, checkbox.checked );
        } );
      }
```

```js
var modes = modeData[ repo ] = [];
```
I believe (but not certain) that our style guide recommends a separate line for each assignment.

I wonder if it is worth lifting all of the modes logic to a more declarative form. It currently looks like:

```js
      if ( isRunnable ) {
        modes.push( {
          name: 'requirejs',
          text: 'Require.js',
          description: 'Runs the simulation from the top-level development HTML in require.js mode',
          url: '../' + repo + '/' + repo + '_en.html',
          queryParameters: devSimQueryParameters.concat( isPhetIO ? phetIOQueryParameters : [] ).concat( simQueryParameters )
        } );
```

But imagine if this was rewritten at the top of the file like so:
```js
var allModes = [{
          name: 'requirejs',
          text: 'Require.js',
          description: 'Runs the simulation from the top-level development HTML in require.js mode',
          url: function(repo){return '../' + repo + '/' + repo + '_en.html';},
          queryParameters: devSimQueryParameters.concat( isPhetIO ? phetIOQueryParameters : [] ).concat( simQueryParameters ),
          matchesRepo: function(repo){}//repo is {string}, returns {boolean} if this mode applies to that repo.
        }];
``` 

I suspect that might be easier for other developers to confidently augment/change in the future.  Not entirely sure if it would work, or if other values would have to become parametrized functions.

**Comment by jonathanolson** [comment]
I believe all of the changes have been made, with the two exceptions:

> I wonder if it is worth lifting all of the modes logic to a more declarative form

That sounds possible (URL, description and matchesRepo would need to change). We'd need it in the populate function, since it depends on knowing which sims are in phet-io, etc.

Might make it harder to identify when modes have the same repos, and functions add a bit of visual overhead.

I don't have a strong preference.

> I'm also wondering if it is necessary/preferable to populate the modeData object on startup, or change things to dynamically get the modes for each repository as it is selected (if that would be simpler).

Populating on start-up seemed simpler, but I'm fine with either approach.

Thoughts?

**Comment by samreid** [comment]
Thanks for making the changes!  I added checkboxes in my prior comment and there are a few items that could still use your help.  Regarding https://github.com/phetsims/phetmarks/issues/11#issuecomment-266510064 I'm fine to leave it as it is.

**Comment by jonathanolson** [comment]
I'm a bit confused, the unselected checkboxes:

>  createRepositorySelector should take a list of repos as the argument, not the mode data.

```js
function createRepositorySelector( repositories ) {
```

> Some parts are a bit difficult for me to read. I'm not sure if it would help more to add documentation or split it up differently:

```js
      get value() {
        var screensValue = screenSelector.value;
        var checkboxes = $( toggleContainer ).find( ':checkbox' );
        var checkedCheckboxes = _.filter( checkboxes, function( checkbox ) {
          return checkbox.checked;
        } );
        var checkboxQueryParameters = _.map( checkedCheckboxes, function( checkbox ) {
          return checkbox.name;
        } );
        var customQueryParameters = customTextBox.value.length ? [ customTextBox.value ] : [];
        var screenQueryParameters = screensValue === 'all' ? [] : [ 'screens=' + screensValue ];
        return checkboxQueryParameters.concat( customQueryParameters ).concat( screenQueryParameters ).join( '&' );
      },
```

Can you clarify what recommended changes are left?

**Comment by samreid** [comment]
> createRepositorySelector should take a list of repos as the argument, not the mode data.

It looks like you already did this, but I missed it.  Thanks, it is checked off now!

> Some parts are a bit difficult for me to read. I'm not sure if it would help more to add documentation or split it up differently:

After getting more familiar with this code, I don't think documentation is need for that code block.  I'll check it off.

**Comment by samreid** [comment]
All set here, thanks @jonathanolson!  Closing.
