### ISSUE TITLE
where should the list of phet-io sims live?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#12]
Over in https://github.com/phetsims/phet-io/issues/645, we recognized that phet-io instrumentation is not getting adequate regression testing.  Contributing to that is the fact that many of us (myself included) don't know which sims have been instrumented, or what the status of instrumentation is.

As a step in the right direction, @jonathanolson added a nifty option to phetmarks for testing sims that have been instrumented for PhET-iO.  It launches test-server with the query parameters needed to test all instrumented sims. Here's a screenshot:

![screenshot_233](https://cloud.githubusercontent.com/assets/3046552/20903455/9190f790-baf8-11e6-86e5-8663ccc7c503.jpg)

The list of sims that have been instrumented is currently hardcoded in phetmarks.js:

```js
  // These are getting instrumented, but may not be completed
  // As well as sims in the process of instrumentation, the
  // completed list of sims can be found here:
  // https://docs.google.com/spreadsheets/d/1ToW8wc9zOFpMglIf63jB1j8YA9Qmh2dxNLH2Sm4qxEo/edit#gid=0
  var phetIORepos = [
    'balloons-and-static-electricity',
    'beers-law-lab',
    'bending-light',
    'build-an-atom',
    'capacitor-lab-basics',
    'charges-and-fields',
    'color-vision',
    'concentration',
    'energy-skate-park-basics',
    'faradays-law',
    'forces-and-motion-basics',
    'gravity-force-lab',
    'molecules-and-light'
  ];
```

While the documentation is nice, I'm skeptical that this will be kept in sync with reality.

Should we move this list to an external file? e.g. `chipper/data/phetio-sims`?

**Comment by jonathanolson** [comment]
Sounds good to me.

**Comment by samreid** [comment]
Yes, a list in chipper seems best.

**Comment by jessegreenberg** [comment]
That sounds good.  I also really like the test PhET-iO option in phetmarks.  I recently broke something in PhET-iO by modifying common code because I didn't know how to test PhET-iO features.

**Comment by pixelzoom** [comment]
12/8/16 consensus: @jonathanolson will move the the list from phetmarks.js to a file in `chipper/data/test-phetio`.  This will be the list of sims that should be regression tested for PhET-iO.

**Comment by jonathanolson** [comment]
Done.
