### ISSUE TITLE
Selected sim is offscreen

### ISSUE THREAD

**Issue by samreid** [phetsims/phetmarks#13]
In https://github.com/phetsims/phetmarks/issues/11#issuecomment-265511994 @samreid said:

1) Make the sim scrolling list smaller (such as 600px tall) or make it autoscroll so the selected item is visible. Often I will open it and it looks like this:

![image](https://cloud.githubusercontent.com/assets/679486/20977569/3e604744-bc63-11e6-9619-f00f039752c0.png)

So that I cannot see what sim is selected.

@jonathanolson said:

> Bleh, it's supposed to auto-scroll. I can look into it.

If it cannot auto-scroll, how about making it a fixed height so it is always on the screen?  That's what I did for the phetmarks launcher, and it worked nicely.

**Comment by jonathanolson** [comment]
I think this is fixed, can you test? (incognito is great here, sometimes it caches the JS still when reloading).

**Comment by samreid** [comment]
It is fixed now, thanks @jonathanolson!
