### ISSUE TITLE
add a11y-view wrapper to phetmarks sim modes

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phetmarks#20]
Would be really convenient if we could launch the a11y-view wrapper from phetmarks.

**Comment by jessegreenberg** [comment]
I think I did this right, @zepumph can you please check me?

**Comment by zepumph** [comment]
That looks very nice. Good addition.

**Comment by zepumph** [comment]
Actually I just saw a nice feature. Currently there is no phet brand default option, so you have to type it manually. It would be nice if it were automatic. I'll take a look.

**Comment by zepumph** [comment]
Fixed I am now loading the a11y view with default phet brand and `ea`. Tagging @jessegreenberg so that he is aware of the change.  Closing

**Comment by jessegreenberg** [comment]
Thanks!
