### ISSUE TITLE
add an aqua test for just a11y sims, with accessibility flag enabled <eom/>

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#24]
From https://github.com/phetsims/scenery/issues/748

**Comment by zepumph** [comment]
Tagging @mbarlow12 and @jessegreenberg so that they know that now in the `aqua` section of phetmarks you can now fuzzMouse and fuzzBoard just a11y sims (defaults to just a11y sims fuzzMouse). @jessegreenberg please review.

**Comment by jonathanolson** [comment]
Would we want testing like this in continuous testing?

**Comment by zepumph** [comment]
Although fuzzBoard option (second two query parameters checked) is likely broken for every sim, I think it is worth adding it so we can fix these problems. The fuzzMouse for specific a11y sims with `?accessibility` would be very good to add (first and third query parameters together).

**Comment by jessegreenberg** [comment]
> When I test coulombs-law, the browser hangs and I can't close the tab, does that happen for you?

Sorry, this might be because of local  copy changes -  I am investigating.

**Comment by zepumph** [comment]
@jonathanolson I will let you know when the keyboard fuzzer is ready for CT, for now please add the following link (adapted for CT) 

http://localhost/aqua/test-server/test-sims.html?ea&audioVolume=0&testDuration=10000&testConcurrentBuilds=4&brand=phet&fuzzMouse&accessibility&testSims=area-model-introduction,balloons-and-static-electricity,build-an-atom,coulombs-law,friction,gravity-force-lab-basics,john-travoltage,molarity,molecules-and-light,ohms-law,plinko-probability,reactants-products-and-leftovers,resistance-in-a-wire,rutherford-scattering

**Comment by zepumph** [comment]
Where the list of testsims is dynamically the list of a11y sims (sorry I'm not being clear). Assigning to @jonathanolson

**Comment by jonathanolson** [comment]
We actually don't run test-sims.html at all from CT, and I'm not aware of support for that to work.

Can I instead add the `?accessibility` query parameter to the a11y sims (anything listed in perennial/data/accessibility), and have that be a separate testable mode for those sims? Would it need other query parameters or annotations?

**Comment by zepumph** [comment]
That will be great! No other query params needed at this time (except fuzzMouse of course). Separate testable mode seems very nice.

Thank you.

**Comment by jonathanolson** [comment]
Automated testing with the ?accessibility flag has been added to continuous testing, and is live.

**Comment by jessegreenberg** [comment]
Thanks @jonathanolson! @zepumph is anything else needed for this issue?

**Comment by zepumph** [comment]
Nope all is good. Once we get fuzzBoard more stable, we will have @jonathanolson add that too, but that will be some time, since it's a pretty low priority I think. Closing
