### ISSUE TITLE
phettest builds are failing

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phetmarks#25]
When using phettest build it shows a failed error.
Log on Turring reads
```
stdout: Fatal error: Unable to find local grunt.
```
Wondering if this could be related to https://github.com/phetsims/joist/issues/519

**Comment by jonathanolson** [comment]
I did some cleanup of repos, `npm config set save false` so we don't run into other issues, and fully updated/pruned npm dependencies for active repos (still finishing up, alphabetically on 'G').

Building seems to be working now. Can you verify?

**Comment by KatieWoe** [comment]
Just tested it on dc construction kit.  It no longer says failed.  However, when I click the built version link after it stops saying running, I get a 404 error.  I may be misunderstanding how it works, as I've never really used build before.  Any help you can give me would be appreciated.

**Comment by jonathanolson** [comment]
It's probably mostly that it hasn't been updated as part of chipper 2.0, so it has the wrong paths (and is building adapted-from-phet brand). I'll want to fix it up first.

**Comment by KatieWoe** [comment]
Just tested on acid base solutions and it seems to be working great!
