### ISSUE TITLE
Phet Dev (HTML) and (Java/Flash) links are broken

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phetmarks#26]
On Phettest the dev links on sims and the Phet Dev (HTML) and Phet Dev (Java/Flash) links do not lead to the proper urls.
Found during https://github.com/phetsims/QA/issues/184

**Comment by jonathanolson** [comment]
Should have been fixed above, can you verify?

**Comment by KatieWoe** [comment]
Looks good.  Should I close?

**Comment by jonathanolson** [comment]
Sure, closing.
