### ISSUE TITLE
Keyboard navigation is buggy

### ISSUE THREAD

**Issue by samreid** [phetsims/phetmarks#27]
Typing the name of a repo, then typing the mode name and pressing enter can launch the mode with the wrong query parameters.  (Using arrow keys or mouse is fine though).  @chrisklus volunteered to investigate.

**Comment by chrisklus** [comment]
@samreid and I found that changing the `addEventListener()` type from 'input' to 'change' listens mouse clicks, arrow keys, and letter keys. Closing.
