### ISSUE TITLE
bug fixes for phet-io related query parameter options

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#28]
Should `phetioValidateTandems` be added as a query parameter checkbox in phetmarks? It seems like it's as important as `ea` for PhET-iO testing, and I seem to be adding it manually a lot since the default changed to false.    

See also https://github.com/phetsims/phet-io/issues/1402, proposal to change the type to `flag`.

**Comment by samreid** [comment]
Added and tested, @zepumph can you please review?

**Comment by zepumph** [comment]
Your commit is good. Perhaps this should default to be on in phetmarks? What do people think? I could go either way. You could always get to the non default validate tandems through the index.

**Comment by samreid** [comment]
@pixelzoom what do you recommend for default?

**Comment by pixelzoom** [comment]
It probably makes sense to use the same default as `ea`.  

Also wondering.... Longterm, do we really need/want `phetioValidateTandems`?  Or should it just be done when assertion are enabled via `ea`?

**Comment by zepumph** [comment]
I will take this over. Currently we add phetioValidateTandems to phet branded links just because it is a phet-io sim. I'll see what I can do.

**Comment by zepumph** [comment]
There are quite a few issues with `phetioValidateTandems` and `phetioDebug` to sort out in phetmarks:
1. Neither of these should ever be an option unless it is a phet-io branded mode (right now `phetioValidateTandems` is by default added to normal phet brand.
2. phetioDebug should not be available unless your mode is a wrapper, and if it is a wrapper this option should be on by default.
3. `ea` should not be provided to any wrappers.
4. `phetioDebug` to appear in wrapper unit tests by default.
5. `ea` to be provided by default to standalone version of the phet-io sim.

**Comment by zepumph** [comment]
All implemented above.
