### ISSUE TITLE
add PhET-iO standalone mode to phetmarks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#29]
Please add a standalone "Mode" to phetmarks, so that a PhET-iO sim can be run standalone without having to navigate to the index wrapper, or use some other indirect workaround.

**Comment by jonathanolson** [comment]
So to clarify, run it with `?brand=phet-io&phetioStandalone&ea` presumably? (like the console colorized phetmark but without the console logging stuff)

**Comment by pixelzoom** [comment]
I think it would be `?brand=phet-io&phetioStandalone`.  Wouldn't `ea` would be determined by settings in "Query Parameters" panel?

**Comment by pixelzoom** [comment]
I confirmed that `console: colorized` mode does not automatically add `ea`, it's dependent on whether "Queary Parameters" `ea` checkbox is checked.

**Comment by pixelzoom** [comment]
👍
