### ISSUE TITLE
phetmarks should be generated, not created by copy-paste of boilerplate

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#3]
I have not been adding my sims to phetmarks, because (a) I don't use it, and (b) it's boilerplate that could be auto-generated and will be difficult to update.  

I don't use it because because I am typically using combinations of query parameters (e.g., ?dev&ea) and/or sim-specific query parameters (e.g. for RPAL ?dev&ea&playAll). It's easier for me to mix and match query parameters by simply adding them to the end of the URL as I need then. So for me, phetmarks isn't very useful.

Assuming the others find phetmarks to be useful... The way it's created (by copy-paste of boilerplate) makes it difficult to add entries for all sims.  The boiler plate is shown below, where 'REPO' is the repository name, and 'TITLE' is the sim title. This could (and should) be generated by reading chipper/data/active-sims (or perhaps active-repos).

``` js
<tr>
    <td><strong><a href="../REPO/REPO_en.html">TITLE</a></strong></td>
    <td class="leftpad">
      <a href="../REPO/build/REPO">build</a>
      <a href="../REPO/REPO_en.html?ea">ea</a>
      <a href="../REPO/REPO_en.html?eall">eall</a>
      <a href="../REPO/REPO_en.html?recordInputEventLog">record</a>
      <a href="../REPO/REPO_en.html?recordInputEventLog=browser">(b)</a>
      <a href="../REPO/REPO_en.html?playbackInputEventLog">playback</a>
      <a href="../REPO/REPO_en.html?playbackInputEventLog=browser">(b)</a>
      <a href="../REPO/REPO_en.html?accessibility">acc</a>
      <a href="../REPO/REPO_en.html?showPointerAreas">areas</a>
      <a href="../REPO/REPO_en.html?fuzzMouse">fuzz</a>
      <a href="../REPO/REPO_en.html?fuzzMouse=100">fuzz100</a>
      <a href="https://github.com/phetsims/REPO">GitHub</a>
      <a href="http://www.colorado.edu/physics/phet/dev/html/REPO/">Dev</a>
      <a href="http://phet.colorado.edu/sims/html/REPO/latest/REPO_en.html">Prod</a>
    </td>
  </tr>
```

**Comment by jonathanolson** [comment]
I use it, and it's fairly convenient when you need to briefly test 10-15 simulations all running assertions, or to quickly jump to locations relevant to certain sims.

None of the sims I've done fully follow that pattern (including unit tests and-or a playground for testing), and common repos aren't terribly consistent. I'd encourage you to put your most commonly-run options into the file and test it out. I'm not sure how we can make adding changes as easily while automating the process.

Copy-paste, auto-selecting all of the repo name and replacing takes at most ~10 seconds for me, and adding/removing entries for each sim is just about as easy.

**Comment by jonathanolson** [comment]
This is dynamically generated now, closing.
