### ISSUE TITLE
Support boolean parameters in phetmarks

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#31]

**Comment by zepumph** [comment]
Added above. @chrisklus would you like to review??

**Comment by chrisklus** [comment]
Looks really good @zepumph! The base phet-io query params vs sim vs wrapper make sense to me and are working as expected, as well as the boolean params.

```js
// [type]: {'boolean'} - if boolean, then it will add "=true" or "=false" to the checkbox value
```

This makes sense to me but `'boolean'` seemed a little weird at first, is this how we notate string booleans?

**Comment by zepumph** [comment]
This is how we annotate the `type` for query parameters, like here from `initialize-globals.js`

```

    /**
     * enables cache busting in requirejs mode.
     */
    cacheBuster: {
      type: 'boolean',
      defaultValue: true
    },

```
