### ISSUE TITLE
phettest fails builds

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/phetmarks#32]
When trying to build a sim off of phettest, the build fails and 
```
jquery-2.1.4.min.js:4 GET http://phettest.colorado.edu:45362/build?sim=make-a-ten 500 (Internal Server Error)
send @ jquery-2.1.4.min.js:4
ajax @ jquery-2.1.4.min.js:4
(anonymous) @ (index):471
```
appears in the console.

**Comment by zepumph** [comment]
I am not able to figure this one out. When trying to test this locally. I get the following error that crashes the server:

```
 Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:227:19)
    at onErrorNT (internal/child_process.js:404:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

Which is one of the most vague errors to be found within Node.js. I added an 'on error' callback so that it wouldn't crash the server. Pull and other commands work just find, but when I try to `npm update` the execute call fails.

**Comment by KatieWoe** [comment]
Not sure if this will be helpful:
I attempted the general troubleshooting for Turing listed in the QA book.  I then tried a build which failed.  Turing's terminal looked like this when I did:
![Image from iOS (1)](https://user-images.githubusercontent.com/41024075/56670874-d7899880-6670-11e9-9c24-6801c603eb79.jpg)

**Comment by zepumph** [comment]
ahh that is lovely thanks! I `ssh`ed to phettest, ran `cd chipper && npm install` and builds work now. I also made sure that builds run npm update in chipper from here on. @KatieWoe please confirm builds work for you now.

**Comment by KatieWoe** [comment]
@zepumph builds do seem to work.  Thanks!

**Comment by KatieWoe** [comment]
Builds on phettest are failing again.

**Comment by KatieWoe** [comment]
Closing due to CT issue
