### ISSUE TITLE
 add "LoL harness" to phetmarks?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#33]
Would it be possible to add "LoL harness" to the **Modes** list in phetmarks?   This would come in handy when working on issues like https://github.com/phetsims/ph-scale/issues/81 and https://github.com/phetsims/ph-scale/issues/88.

**Comment by pixelzoom** [comment]
There's apparently also a `legendsOfLearning` query parameter that would be nice to add to **Query Parameters** list.

**Comment by samreid** [comment]
If we add a phetmarks link to LOL, it will probably include the Query Parameter for the iframe part of the URL.  That seems sufficient, I don't think a separate entry for `legendsOfLearning` query parameter by itself would be too useful.

**Comment by jessegreenberg** [comment]
It looks like the url query parameter puts the right source url in their test harness
http://developers.legendsoflearning.com/public-harness/index.html?url=http://localhost:8080/energy-skate-park/energy-skate-park_en.html?brand=phet%26ea%26legendsOfLearning

**Comment by jessegreenberg** [comment]
I added a Legends of Learning mode in the above commit with `brand=phet` and `ea`. We could support user selected query parameters too, but I didn't see a quick way to do this and I wasn't sure if it was necessary for legends of learning testing.

**Comment by pixelzoom** [comment]
7/25/19 dev meeting: 

No need to support additional query parameters via phetmarks.  The typical use case is simply to run the LoL harness.  If you need additional query parameters, add them manually.  Closing.
