### ISSUE TITLE
Add support for boolean query parameters

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#35]
From phetsims/chipper#541. Right now we only support flags. Which makes the cacheBust quite strange:

![image](https://user-images.githubusercontent.com/6856943/68892480-9bcb2480-06cf-11ea-90a6-b3eb6865c643.png)

Ideally if the checkbox wasn't checked, then it would have `cacheBust=false`, and if it was checked then the query string would have `cacheBust=true`.

**Comment by pixelzoom** [comment]
Moved to #37. Closing.
