### ISSUE TITLE
add ability to turn off sound via phetmarks

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#36]
As more sound support is being added, having sound on by default is a bit annoying, and has resulted in me making sound in inappropriate settings lately.   

We could add the `sound` query parameter to the "Query Parameters" section of phetmarks.  It would need to be a radio button group, not a checkbox:

```js
    sound: {
      type: 'string',
      defaultValue: 'enabled',
      validValues: [ 'enabled', 'disabled', 'muted' ]
    },
```

Even better (easier?) would be if we could provide query parameters in the phetmarks URL, have those set the "Query Parameter" checkboxes,  and pass them through to sims.   That would allow me to bookmark `http://localhost/.../phetmarks?sound=disabled` and not have to remember to change things in phetmarks.

**Comment by ariel-phet** [comment]
I have also found myself turning off sound when doing testing, this seems like a potentially quick fix, so marking as high priority.

**Comment by pixelzoom** [comment]
On second thought.... Having to select a radio button in phetmarks isn't any easier than having to click the sound button in the sim's navigation bar after it starts up.   So pass-through query parameters would be the preferred solution.

**Comment by samreid** [comment]
We discuss the passthrough regarding cache busting in this issue: https://github.com/phetsims/chipper/issues/541#issuecomment-554058613

**Comment by pixelzoom** [comment]
1/23/20 dev meeting:

Pass-through query parameters would be best. I'll self-assign and investigate. If it's more than 1 hour of work, I'll likely punt and just use the sound button in the sim's navigation bar.

**Comment by samreid** [comment]
Does this patch implement passthrough correctly?

```diff
Index: js/phetmarks.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phetmarks.js	(revision 8407c7c1e60adfe6c5702ecddc1210720827fad8)
+++ js/phetmarks.js	(date 1579808898272)
@@ -719,7 +719,7 @@
 
     function getCurrentURL() {
       const queryParameters = queryParameterSelector.value;
-      const url = modeSelector.mode.url;
+      const url = modeSelector.mode.url + window.location.search;
       const separator = url.indexOf( '?' ) < 0 ? '?' : '&';
       return url + ( queryParameters.length ? separator + queryParameters : '' );
     }
```

**Comment by pixelzoom** [comment]
Nope, that patch doesn't do the job.  It can result in pass-through where query parameters are repeated, which is not allowed by QueryStringMachine. 

For example, if I launch `.../phetmarks/?screens=3`, then select screen "2" in the Query Parameters section of phetmarks, my sim will be launched with this URL:

`.../acid-base-solutions_en.html?screens=3&brand=phet&ea&screens=2`

which results in this failure in QueryStringMachine:

```js
QueryStringMachine.js?bust=1579826875831:643 Uncaught Error: Query String Machine Assertion failed: query parameter cannot occur multiple times
    at queryStringMachineAssert (QueryStringMachine.js?bust=1579826875831:643)
    at parseValues (QueryStringMachine.js?bust=1579826875831:512)
    at Object.getForString (QueryStringMachine.js?bust=1579826875831:145)
    at Object.getAllForString (QueryStringMachine.js?bust=1579826875831:18
```

**Comment by pixelzoom** [comment]
Here's the relevant function in phetmarks.js:

```js
    function getCurrentURL() {
      const queryParameters = queryParameterSelector.value;
      const url = modeSelector.mode.url;
      const separator = url.indexOf( '?' ) < 0 ? '?' : '&';
      return url + ( queryParameters.length ? separator + queryParameters : '' );
    }
```

`queryParameters` is a string for what's set in the "Query Parameter" section of the  phetmarks UI. E.g. `brand=phet&ea&screens=2` in my example above.

`window.location.search` (as @samreid pointed out above) is a string containing the query parameters part of the URL that was used to run phetmarks.  E.g. `?screens=3` in my example above.

I've found no easy way to merge these 2 strings.  

Furthermore, values in the URL used to launch phetmarks should set the "Query Parameters" section of the phetmarks UI.   There's no easy way to do that, and the current design of the "Query Parameters" UI makes it downright impossible. Examples: `brand` is a `{string}`, but phetmarks provides a checkbox;  `screens` is a list of integers, phetmarks provides a radio button for selecting one (possibly invalid) integer.  Etc.  

So I'm punting on this, and will be using the sim's sound button to disable sound.

Assigning to @ariel-phet in case you want to investigate redesigning the phetmarks "Query Parameter" UI so that pass-through query parameter are someday possible.  If not, feel free to close.

**Comment by samreid** [comment]
With the patch, `http://localhost/phetmarks/?sound=muted` would mute all links, and could not conflict with values specified in the UI, since there is no UI control for `?sound`.  Would this not be an improvement to your workflow?  If not, why not?

**Comment by pixelzoom** [comment]
Implementing pass-through query parameters clearly has general problems. And I'm not going to be the one to add a hack/landmine just to support my workflow.

**Comment by samreid** [comment]
How about this compromise?  If the user specifies a query string in the studio URL, then the other UI elements for setting query parameters are not shown?  It's basically saying "I'm taking query parameters into my own hands".  It would look like this:

![image](https://user-images.githubusercontent.com/679486/73045196-2d6eb500-3e2a-11ea-9b20-5660cdafabbe.png)

Here's a first draft patch that accomplishes this:

<details>

```diff
Index: js/phetmarks.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/phetmarks.js	(revision 8407c7c1e60adfe6c5702ecddc1210720827fad8)
+++ js/phetmarks.js	(date 1579842052126)
@@ -457,7 +457,7 @@
             group: 'PhET-iO',
             description: 'Runs the phet-io wrapper ' + wrapperName,
             url: url,
-            queryParameters:queryParameters
+            queryParameters: queryParameters
           } );
         } );
 
@@ -718,7 +718,9 @@
     const queryParameterSelector = createQueryParameterSelector( modeSelector );
 
     function getCurrentURL() {
-      const queryParameters = queryParameterSelector.value;
+      const queryParameters = window.location.search.length > 0 ?
+                              window.location.search.substring( 1 ) :
+                              queryParameterSelector.value;
       const url = modeSelector.mode.url;
       const separator = url.indexOf( '?' ) < 0 ? '?' : '&';
       return url + ( queryParameters.length ? separator + queryParameters : '' );
@@ -764,7 +766,9 @@
     queryParametersDiv.appendChild( resetButton );
     document.body.appendChild( repoDiv );
     document.body.appendChild( modeDiv );
-    document.body.appendChild( queryParametersDiv );
+    if ( window.location.search.length === 0 ) {
+      document.body.appendChild( queryParametersDiv );
+    }
 
     function updateQueryParameterVisibility() {
       queryParametersDiv.style.visibility = modeSelector.mode.queryParameters ? 'inherit' : 'hidden';

```

</details>

You can still cause interference if you use one of the mode's query parameters.  For instance, studio specifies "sim=...", so if you navigated to http://localhost/phetmarks/?sim=balancing-act, then you could end up with an error.  But that seems like a rare case and a clear error message if you do something like that.

So in practice, you could use a URL like: http://localhost/phetmarks/?sound=muted&brand=phet&ea to take care of sound, brand and assertions.

**Comment by pixelzoom** [comment]
While I appreciate the attempt to make this work, this still feels like a hack. The correct solution is to make phetmarks set "Query Parameters" based on `window.location.search`, not totally remove that part of the UI.   And I reply heavily on the "Query Parameters" section when testing phet-io, especially Studio.   So if I'd need to either set up multiple book marks for phetmark, or have a different workflow for Studio.   Easier for me to just get in the habit of hitting the sound button in the navigation bar.

**Comment by ariel-phet** [comment]
@pixelzoom could you close this issue and open a new one that is something to the effect of "improvements to query parameters UI and handling in phetmarks"? Just put your thoughts in as to potential future improvements.

This would be future work, but it might be something worth chipping away at, as I feel like our phetmarks bare-bones UI is the first stepping stone to what we eventually want for our website (a UI where teachers could choose basic sim customization and generate the correct URL and query parameters). 

On a side-note for your workflow, aren't there options for muting specific applications/browser tabs? Then hopefully you could do that once and then not have to click the same button each time you reload?

https://www.howtogeek.com/231959/how-to-mute-individual-browser-tabs-in-chrome-safari-and-firefox/

**Comment by pixelzoom** [comment]
> @pixelzoom could you close this issue and open a new one

https://github.com/phetsims/phetmarks/issues/37

> ... options for muting specific applications/browser tabs ...

Thanks, I might make use of that. If I mute http://localhost/~cmalley/GitHub, all sims run from my working copy are muted.  My concern with using that as a general solution is that someone (like me:) may forget that they've muted a site, and think that sound is broken. And the indicator in Chrome is not very obvious, see tiny icon at right end of URL field in screenshot below.

<img width="1211" alt="screenshot_70" src="https://user-images.githubusercontent.com/3046552/73286890-943af800-41b5-11ea-9dfe-b5f77f196293.png">
