### ISSUE TITLE
Add `phetioPrintMissingTandems` to phetmarks for mode=studio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#39]
From https://github.com/phetsims/phet-io/issues/1612#issuecomment-581536461:

Add `phetioPrintMissingTandems` to phetmarks for mode=studio.

**Comment by pixelzoom** [comment]
First order of business is to unfold this mess in phetmarks.js:

```js
          const queryParameters = wrapperName === 'studio' ?
                                  phetioWrapperQueryParameters.concat( {
                                    value: 'phetioElementsDisplay=all',
                                    text: 'Show all elements',
                                    default: true
                                  } ) : wrapperName === 'playback' ? [] :
                                        phetioWrapperQueryParameters;
```

**Comment by pixelzoom** [comment]
Relevant code has been cleaned up (see https://github.com/phetsims/phetmarks/commit/88fb79fbcbd98ea4f934143677dd2483090e0b9e) and `phetioPrintMissingTandems` checkbox added for Studio (see https://github.com/phetsims/phetmarks/commit/8d7b6b0d1162078eb784bb22758bcea47b0892c9). 

And the lucky reviewer is....

```
> _.sample( [ 'CK', 'MK', 'SR' ] )
"MK"
```

**Comment by zepumph** [comment]
You changes look excellent! Thanks for the conditional improvement too.
