### ISSUE TITLE
New phettest features

### ISSUE THREAD

**Issue by phet-steele** [phetsims/phetmarks#4]
I made these phettest feature suggestions to @jonathanolson to implement:
1. Display a red text warning near the top saying something like "There have been changes to common code since last pull, please Pull All."
2. Display something like a timestamp or latest commit (or both?) next to sim names to be able to see the last time the sim was pulled, and if another pull is needed.

**Comment by jonathanolson** [comment]
Changes made, let me know if anything else is needed, or if there are any bugs.

**Comment by phet-steele** [comment]
Unassigning until something comes up.

**Comment by phet-steele** [comment]
> Unassigning until something comes up.

What does this even mean @phet-steele? Why didn't you just close this @phet-steele? @jonathanolson did a great job after all.
