### ISSUE TITLE
phetmarks can't be linted

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#40]
Discovered while working on #39.  phetmarks repo isn't set up to be linted.  This caused my git pre-commit hook to fail.  

Assigning to @ariel-phet to prioritize and assign.

**Comment by zepumph** [comment]
Should be fixed now. @pixelzoom please test by:

```
cd phetmarks
npm install
grunt lint
```

**Comment by pixelzoom** [comment]
Verified, thanks! Closing.
