### ISSUE TITLE
Don't cache phettest

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#42]
I was wondering if this would make life easier for people who use this a lot. I'm not terribly skilled in Apache config files. 

@mattpen what do you think about me adding the `CacheDisable on` directive in the `Directory` tag for phettest?

Does that seem like the right thing to do?

**Comment by mattpen** [comment]
I've never used this directive, but it sounds like a fine idea to me.  You'll probably want to verify that the mod_cache module is available on phettest.  I've never used that module, so I'm not sure if it is standard or not.

**Comment by zepumph** [comment]
I added 

```
<filesMatch ".(js)$">
    Header set Cache-Control "no-store"
</filesMatch>

```

to the .htaccess file in the phettest directory. I confirmed by looking in the chrome network tab in dev tools that the `no-store` is coming in the response. I think this is all that is needed. I will let slack know.
