### ISSUE TITLE
aqua test 'Test Sims (Load Only)' is fuzzing

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#43]
I was hoping to do a quick test of loading all sims using aqua.  That test is doesn't work as advertised - it fuzzes every sim for 10 seconds.

In phetmarks.js:

```js
const generalTestParams = 'ea&audioVolume=0&sound=disabled&testDuration=10000&testConcurrentBuilds=4';
const fuzzTestParameter = [ {
  value: generalTestParams + '&brand=phet&fuzz',
  text: 'Test PhET sims',
  default: true
} ];

...

modes.push( {
  name: 'test-sims-load-only',
  text: 'Test Sims (Load Only)',
  description: 'Runs automated testing that just loads sims (without fuzzing or building)',
  url: '../aqua/test-server/test-sims.html',
  queryParameters: fuzzTestParameter
} );
```

So the 'Test Sims (Load Only)' test is documented as "without fuzzing".  But it runs with ?fuzz.

**Comment by pixelzoom** [comment]
I changed the query parameters for 'Test Sims (Load Only)' to `ea&testDuration=3000&testConcurrentBuilds=1` in the above commit.   No idea if that's correct, but it worked for my use case. 

@ariel-phet please assign someone familiar with phetmarks to review (and probably correct).

**Comment by jonathanolson** [comment]
Ahh looks like the query parameters got dropped in https://github.com/phetsims/phetmarks/commit/0a75b97d0adbf954a5707de5dcffc863b6af302b#diff-2088d6bf0e98a3e249674e2ba9506bbe. I'll fix it up.

**Comment by jonathanolson** [comment]
@pixelzoom can you verify? (Also phetmarks likes to be cached FYI)

**Comment by pixelzoom** [comment]
Looks good, thanks! Closing.
