### ISSUE TITLE
Radio Button code is copy/pasted

### ISSUE THREAD

**Issue by samreid** [phetsims/phetmarks#44]
From https://github.com/phetsims/tandem/issues/198

@zepumph pointed out code I copied and pasted:

> The implementation is unfortunate. Almost 100% of this control is duplicated from the screens radio button selector. This is because we have no general solution for radio buttons yet:

```

  function createScreenSelector() {
    const div = document.createElement( 'div' );

    function createScreenRadioButton( name, value, text ) {
      const label = document.createElement( 'label' );
      label.className = 'screenLabel';
      const radio = document.createElement( 'input' );
      radio.type = 'radio';
      radio.name = name;
      radio.value = value;
      radio.checked = value === 'all';
      label.appendChild( radio );
      label.appendChild( document.createTextNode( text ) );
      return label;
    }

    div.appendChild( createScreenRadioButton( 'screens', 'all', 'All screens' ) );
    for ( let i = 1; i <= 6; i++ ) {
      div.appendChild( createScreenRadioButton( 'screens', '' + i, '' + i ) );
    }

    return {
      element: div,
      get value() {
        return $( 'input[name=screens]:checked' ).val();
      },
      reset: function() {
        $( 'input[name=screens]' )[ 0 ].checked = true;
      }
    };
  }

  function createPhetioValidationSelector() {
    const div = document.createElement( 'div' );

    function createValidationRadioButton( name, value, text ) {
      const label = document.createElement( 'label' );
      label.className = 'validationLabel'; // https://github.com/phetsims/tandem/issues/191
      const radio = document.createElement( 'input' );
      radio.type = 'radio';
      radio.name = name;
      radio.value = value;
      radio.checked = value === 'simulation-default';
      label.appendChild( radio );
      label.appendChild( document.createTextNode( text ) );
      return label;
    }

    const span = document.createElement( 'span' );
    span.textContent = 'PhET-iO Validation:';
    div.appendChild( span );
    div.appendChild( createValidationRadioButton( 'validation', 'simulation-default', 'Simulation Default' ) );
    div.appendChild( createValidationRadioButton( 'validation', 'true', 'True' ) );
    div.appendChild( createValidationRadioButton( 'validation', 'false', 'False' ) );

    return {
      element: div,
      get value() {
        return $( 'input[name=validation]:checked' ).val();
      },
      reset: function() {
        $( 'input[name=validation]' )[ 0 ].checked = true;
      }
    };
  }
```

> We should close this issue, and try to make https://github.com/phetsims/phetmarks/issues/37 happen. 

I'm not planning to work on this in the near future, so leaving it unassigned.  Anyone feel free to reprioritize or reassign.

**Comment by zepumph** [comment]
We have the opportunity to copy paste this again over in https://github.com/phetsims/phet-io-wrappers/issues/629. I'll see about refactoring and generalizing things to see if it works well. Good luck us!

**Comment by zepumph** [comment]
Alright, this file is in pretty good shape at this time. I'm really happy with the progress, and we now have 4 usages of the new `parameterValues` query parmater type. (soon to be 5 over in https://github.com/phetsims/phet-io-wrappers/issues/629).

@samreid. I wanted you to be aware of this, but I don't think it is worth too heavy of a review. I think we should close this issue, but let me know if you want to discuss anything else.

**Comment by zepumph** [comment]
Ok awesome. I'm feeling really good here. Anything else that you can think of?

I'm planning to mention this in dev meeting Thursday.

**Comment by samreid** [comment]
I skimmed through the recent changes in phetmarks.ts and the direction seems really great. Some things like `QueryParametersSelector` could possibly be changed from a type alias into a class, then instead of `create...` methods it would be a constructor. But that has pros and cons, so not sure if it is a net benefit.  Want to keep this open for Thursday? Up to you @zepumph

**Comment by zepumph** [comment]
>I'm planning to mention this in dev meeting Thursday.

I mentioned it last week. I think classes could be nice, but not really necessary in its current state. I'll keep the suggestion in mind. Closing

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
