### ISSUE TITLE
Add a "sound board" to the PhET Testing Server (phettest)

### ISSUE THREAD

**Issue by jbphet** [phetsims/phetmarks#45]
In a recent sound design meeting, our chief sound designer requested the ability to have a "sound board" for each sim.  A sound board is a single place where one can go to hear all of the sounds associated with a sim without having to search around for them in the sim to figure out how they are triggered and what is there.  Here is a screenshot and a link for an example soundboard with several clips from a movie that we could use as a model:

![image](https://user-images.githubusercontent.com/3082831/96522470-aae81a00-1230-11eb-8f6a-fba4473818b5.png)

Link: reference this: https://www.101soundboards.com/boards/23199-shrek-soundboard

I'm thinking that the phettest server would be a good spot for this, since it is already pulling code from GitHub into a set of directories and doing things with it.

**Comment by jbphet** [comment]
@jonathanolson - would you have any objections to me adding functionality like this to phettest?  I'm thinking a single link on the main page, and from there the user would choose the simulation, then get a page similar to what is shown above.

**Comment by jbphet** [comment]
In the 10/20/2020 sound design meeting we discussed putting this into phetmarks instead of just having it phet-test.  The proposal is to make it somewhat similar to the a11y view.

**Comment by Ashton-Morris** [comment]
![Screen Shot 2020-10-27 at 11 42 56 AM](https://user-images.githubusercontent.com/34492870/97366857-adb8bf80-186d-11eb-99e6-3065093e863d.png)

Here is a starter mockup

**Comment by jbphet** [comment]
We discussed this at the 1/26/2021 sound design meeting, and here are a couple of decisions:
- We want to have all the sims in one place instead of having a page per sim.  This implies a different approach than a11y view, and we will likely have a separate repo where this is pulled together into one set of HTML and JavaScript.
- It would be nice to be able to optionally load the sim into an iframe so that sounds can be tried and compared in context
- @emily-phet pointed out that some of this is similar to what was done for the 'binder' project, so perhaps some of that work can be leveraged
- It would be nice, and more usable, if the individual sims can be collapsed
- It would be nice to be able to open all using a shortcut, so that users can more easily peruse all sounds that are available
- Another good short cut would be "play all sounds", where it would sequentially go through them all
  - There should be a way in this feature to stop it and move backwards in order to find a sound
  - A thought from the meeting: Having a player for each sim, and then one for all sounds, that would play them in sequence and allow users pause and move forward and backward within the sound list would be nice
- Arrow navigation between sounds would be a good feature

**Comment by jonathanolson** [comment]
> would you have any objections to me adding functionality like this to phettest?

Sounds great to me.

**Comment by jbphet** [comment]
After doing some prototyping and then presenting the prototype in the 2/25/2021 sound design meeting, a few more decisions were made, namely:

- This should exist in its own repo and be accessible through phetmarks.  Part of this process will be to add it to `active-repos`
- Having an update step to rebuild it when needed is okay, but at some point we might want to consider making it dynamic so that it doesn't need to be updated
- The prototype should be reviewed in the next sound design meeting and we can discuss whether common-code sounds should be present for each repo.  If so, @zepumph suggested the webpack could be used to make the determination as to what sounds are used.

**Comment by jbphet** [comment]
An initial version of the soundboard has been created and is available in the `skiffle` repository.  As of this moment, it is functional and looks like this:

![image](https://user-images.githubusercontent.com/3082831/115477144-84676380-a200-11eb-8e70-597232c9b607.png)

I'm going to close this issue and will do further work under issues in the `skiffle` repo.
