### ISSUE TITLE
"Compare with reference API" option in phetmarks fails hard

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#49]
Attempting to use the new "Compare with reference API" option in phetmarks, like this:

<img width="850" alt="screenshot_922" src="https://user-images.githubusercontent.com/3046552/111665687-96587f80-87d8-11eb-8309-e465f4d1e77e.png">

The URL it generates is:

http://.../studio/?sim=graphing-quadratics&phetioCreateArchetypes&phetioCompareAPI&phetioDebug&phetioElementsDisplay=all&phetioValidation=true

It fails hard: 

```
QueryStringMachine.js:681 Uncaught Error: Query String Machine Assertion failed: query parameter cannot occur multiple times
    at queryStringMachineAssert (QueryStringMachine.js:681)
    at parseValues (QueryStringMachine.js:559)
    at Object.getForString (QueryStringMachine.js:154)
    at Object.getAllForString (QueryStringMachine.js:214)
    at Object.getAll (QueryStringMachine.js:130)
    at phet-io-initialize-globals.js:168
    at phet-io-initialize-globals.js:192
```

**Comment by samreid** [comment]
Until that's fixed, you can use it in Standalone:

![image](https://user-images.githubusercontent.com/679486/111666159-1383f480-87d9-11eb-8eb5-ca5234e89354.png)

**Comment by pixelzoom** [comment]
Zooom'ed briefly with @samreid and @zepumph.  Studio adds an additional `phetioCreateArchetypes` to the URL, so that's the duplicate query parameter.

Given that QueryStringMachine does not allow duplicate query parameters in a URL, it's generally poor form to add ANY query parameter to a URL without first checking whether it already exist in the URL.

**Comment by zepumph** [comment]
The above commit supports standalone and studio, but not other wrappers. @samreid what do you think?

**Comment by samreid** [comment]
Was our plan to make it so that `phetioCompareAPIs` works without having to specify `phetioCreateArchetypes`?

**Comment by zepumph** [comment]
Oh that's right. Thanks.

**Comment by zepumph** [comment]
The above is minor cleanup about ?phetioCreateArchetypes. query parameters should not be mutated, especially since we have `phetio.createArchetypes` which should be used instead.

**Comment by zepumph** [comment]
How's that @samreid? I tried to make things as flexible as possible, and updated CT and phetmarks too.

**Comment by samreid** [comment]
The code changes look good, and I tested phetmarks and it also seemed good.  I tested in natural selection/studio with the query parameter and it worked properly, and I noticed that once CT gets around to testing that again, it will fail due to breaking changes.  Closing.
