### ISSUE TITLE
phettest-server validateSimName preventing some sims from pulling

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/phetmarks#51]
In order to pull or build, phettest-server requires the repo have a name with all lower-case and hyphens.   @KatieWoe noticed that this was causing the QA repo (which was recently added to active-repos) to fail to pull on phettest.

![image](https://user-images.githubusercontent.com/6396244/120719402-32b92680-c498-11eb-96e1-ee758970771b.png)

Would it be OK to remove this check for pull? Or should we make an exception for QA? Asking @jonathanolson because I think he is an author of phettest-server.

**Comment by samreid** [comment]
Alternatively, we could rename QA to be lowercase?

**Comment by jonathanolson** [comment]
I'm curious what the cost of renaming would be. I'm also open to making a distinction between "repos that have a package.json and follow those rules" and "other repos".

Would our issue links break? If it's recommended by others, let's see if renaming is painless?

**Comment by samreid** [comment]
How about a quick dev-meeting discussion/vote?

**Comment by samreid** [comment]
Dev meeting: We could try renaming it, and test out the problems.

@chrisklus volunteered to test it and check the links.  If there are too many severe problems, we can revert the naming.

**Comment by chrisklus** [comment]
As posted on Slack, this QA was renamed to qa (https://github.com/phetsims/qa). Please either remove your existing local QA repo and run `clone-missing-repos.sh` or rename it to `qa` and run `git remote set-url origin https://github.com/phetsims/qa.git` in the `qa` directory.

I will close after a couple days if no trouble comes up.

**Comment by chrisklus** [comment]
I think this issue is good to go, closing.
