### ISSUE TITLE
npm update perennial-alias

### ISSUE THREAD

**Issue by samreid** [phetsims/phetmarks#55]
Discovered in https://github.com/phetsims/number-line-distance/issues/64, and also caused by https://github.com/phetsims/chipper/issues/1018 where we introduced perennial-alias, we need to npm update perennial-alias since the server is saying:

```
3|phettest | stdout: >> Error: Cannot find module 'winston'
3|phettest | >> Require stack:
3|phettest | >> - /data/web/htdocs/dev/phettest/perennial-alias/js/dual/execute.js
3|phettest | >> - /data/web/htdocs/dev/phettest/chipper/js/grunt/copySupplementalPhetioFiles.js
3|phettest | >> - /data/web/htdocs/dev/phettest/chipper/js/grunt/buildRunnable.js
3|phettest | >> - /data/web/htdocs/dev/phettest/chipper/js/grunt/Gruntfile.js
3|phettest | >> - /data/web/htdocs/dev/phettest/energy-forms-and-changes/Gruntfile.js
3|phettest | >> - /data/web/htdocs/dev/phettest/energy-forms-and-changes/node_modules/grunt/lib/grunt/task.js
3|phettest | >> - /data/web/htdocs/dev/phettest/energy-forms-and-changes/node_modules/grunt/lib/grunt.js
3|phettest | >> - /usr/lib/node_modules/grunt-cli/bin/grunt
3|phettest | 
3|phettest | stdout: Warning: Task "default" not found. Use --force to continue.
3|phettest | 
3|phettest | stdout: 
3|phettest | 
3|phettest | stdout: Aborted due to warnings.
```

**Comment by samreid** [comment]
@jessegreenberg and I were shocked to see that npm update on an updated perennial takes so long:

```
[phet-admin@bayes perennial]$ time npm update

real	1m36.732s
```

**Comment by samreid** [comment]
@jessegreenberg and I applied a band-aid, where perennial-alias is `npm updated` for now, but we weren't sure how to thread that `npm update` properly.  @zepumph or @jonathanolson can you please advise?  We tried something in the commit above, but it exited after first success, and didn't let the other finish (we think).  Also, why is `npm update` taking 1m36s on an up-to-date repo?

**Comment by zepumph** [comment]
I'll look into phettest build support next.

**Comment by jonathanolson** [comment]
Maybe clear the npm cache and see if it improves?

**Comment by zepumph** [comment]
Great idea! I confirmed this is a cache problem:

```
[phet-admin@bayes perennial-alias]$ time npm update --cache ~/tmp/phettest-perennial-npm-cache

real    0m2.439s
user    0m2.052s
sys     0m0.253s


```
@jonathanolson can you confirm that I won't be causing any downstream problems by "nuking" our npm cache on bayes?

**Comment by jonathanolson** [comment]
> @jonathanolson can you confirm that I won't be causing any downstream problems by "nuking" our npm cache on bayes?

Nuking the cache has been done once or twice on bayes when it was slow, seemed to help a bit. Confirmed not a problem.

**Comment by zepumph** [comment]
After the above commit, we are updating perennial-alias, this was only tested locally, I'll update bayes now.

**Comment by zepumph** [comment]
I pulled phetmarks on bayes, and then ran `pm2 restart phettest-server`. I then opened phettest in a browser and refreshed perennial, here were the logs:

```

3|phettest-server  | running git pull from /data/web/htdocs/dev/phettest/perennial
3|phettest-server  | stdout: Already up-to-date.
3|phettest-server  | finished executing git [ 'pull' ] /data/web/htdocs/dev/phettest/perennial 0
3|phettest-server  | running npm update from /data/web/htdocs/dev/phettest/perennial
3|phettest-server  | finished executing npm [ 'update' ] /data/web/htdocs/dev/phettest/perennial 0
3|phettest-server  | running bash /data/web/htdocs/dev/phettest/perennial/bin/clone-missing-repos.sh from /data/web/htdocs/dev/phettest/
3|phettest-server  | finished executing bash [
3|phettest-server  |   '/data/web/htdocs/dev/phettest/perennial/bin/clone-missing-repos.sh'
3|phettest-server  | ] /data/web/htdocs/dev/phettest/ 0
3|phettest-server  | running git pull from /data/web/htdocs/dev/phettest/perennial-alias
3|phettest-server  | stdout: Already up-to-date.
3|phettest-server  | finished executing git [ 'pull' ] /data/web/htdocs/dev/phettest/perennial-alias 0
3|phettest-server  | running npm update from /data/web/htdocs/dev/phettest/perennial-alias
3|phettest-server  | finished executing npm [ 'update' ] /data/web/htdocs/dev/phettest/perennial-alias 0
3|phettest-server  | running bash /data/web/htdocs/dev/phettest/perennial/bin/clone-missing-repos.sh from /data/web/htdocs/dev/phettest/
3|phettest-server  | finished executing bash [
3|phettest-server  |   '/data/web/htdocs/dev/phettest/perennial/bin/clone-missing-repos.sh'
3|phettest-server  | ] /data/web/htdocs/dev/phettest/ 0
```


While this clones missing repos twice, I don't think it is a big deal. I think we are ready to close. Over to @samreid. Anything else?

**Comment by zepumph** [comment]
Note https://github.com/phetsims/phetmarks/issues/56 for updating doc like we talked about.

**Comment by samreid** [comment]
I reviewed the commit and it seemed reasonable, thanks!  Closing.
