### ISSUE TITLE
How to phettest locally (for testing)

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#56]
I discovered while working on https://github.com/phetsims/phetmarks/issues/55 that it is quite challenging to debug phettest and its server from bayes. It is much nicer to have a local way of testing this. I'll explain how I was able to set it up locally, and then this issue will be for optimizing this further, and making sure to document it. 

Here is a patch that outlines a fair number of these steps. I don't think committing this makes sense because it feels like a workaround.

<details>

```diff
Index: phettest/index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/phettest/index.html b/phettest/index.html
--- a/phettest/index.html	(revision 589cdbe7c499adfc1cc478b11340fc0ac61ff93d)
+++ b/phettest/index.html	(date 1628701068282)
@@ -123,6 +123,6 @@
 <script type="text/javascript" src="sherpa/lib/jquery-2.1.0.min.js"></script>
 <script type="text/javascript"
         src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
-<script type="text/javascript" src="phettest.js"></script>
+<script type="text/javascript" src="./phetmarks/phettest/phettest.js"></script>
 </body>
 </html>
Index: phettest/phettest.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/phettest/phettest.js b/phettest/phettest.js
--- a/phettest/phettest.js	(revision 589cdbe7c499adfc1cc478b11340fc0ac61ff93d)
+++ b/phettest/phettest.js	(date 1628698176955)
@@ -2,8 +2,8 @@
 
 // will be replaced by domain name in the future
 const domain = 'https://bayes.colorado.edu/dev/';
-const serverURL = `${domain}phettest-server/`;
-const phettestURL = `${domain}phettest/`;
+const serverURL = `http://localhost:45362/`;
+const phettestURL = `http://localhost:8080/phetmarks/phettest/`;
 
 // common repo fields
 const commonSameMasterStatusElements = {};
@@ -227,10 +227,10 @@
   $.ajax( `${serverURL}perennial-refresh` ).done( data => {
     $( status ).text( '' );
 
-    updateCommonRepos();
-    updateSims();
-    updateCommonCheckingStatus( false );
-    updateSimCheckingStatus( false );
+    // updateCommonRepos();
+    // updateSims();
+    // updateCommonCheckingStatus( false );
+    // updateSimCheckingStatus( false );
   } ).fail( () => {
     $( status ).text( 'perennial refresh failed' );
   } );
@@ -316,7 +316,7 @@
       } );
 
       updateAllCommon();
-      checkCommonSameMaster();
+      // checkCommonSameMaster();
     } );
   } );
 }
@@ -403,14 +403,12 @@
     } );
 
     updateAllSims();
-    checkSimSameMaster();
+    // checkSimSameMaster();
   } );
 }
 
 updateCommonRepos();
 updateSims();
-updateCommonCheckingStatus( false );
-updateSimCheckingStatus( false );
 commonFilter( false );
 simFilter( false );
   
\ No newline at end of file

```

</details>

1. move the index.html to the root of your git repository structure, and change the link to phettest.js to point into ./phetmarks/phettest/phettest.js
3. `cd ./phetmarks/phettest/phettest-server.js`
4. `node phettest-server.js`
2. change the hard coded URLs at the top phettest.js to point to the local URLs you plan to use.
3. For my work in updating how to refresh perennial, it was helpful to stop the commands that occur one sim at a time and on launch of the page. (also in the patch).
5. navigate via your normal method to the root of your directories. It will be phettest.

In addition to this, I found that some commands had to change to support windows platforms.

**Comment by zepumph** [comment]
Committed above. @samreid can you review in whatever way you would like. From going through the instructions and trying to run it locally (more work), to just glancing through the doc (less work). Whatever you'd like is good with me. Feel free to close.

**Comment by zepumph** [comment]
>but leaves me wondering if we can eliminate several steps if we just update phettest so that it runs from phetmarks/index.html instead of having to pop it up to index.html

This step is not needed on the server, because of htaccess directives. It is mostly just a hack for testing locally.

I remember trying to accomplish what you are recommending when working on phettest last time (I believe when moving it to bayes), but giving up. I'm not currently in a position to devote more resources to phettest, and feel like it is nice for the index page to be at the root of the directory structure, i.e. `phettest/` instead of `phettest/phetmarks/phettest/`.

I feel ready to close.

**Comment by samreid** [comment]
Sounds good, let's close.  @jonathanolson and I may take it for a test drive as part of https://github.com/phetsims/chipper/issues/1073

**Comment by samreid** [comment]
I tested this in https://github.com/phetsims/chipper/issues/1073 and it worked great.  I got tricked for a while because I forgot a slash after the port.  I'll add a note about that to protect me next time.  Here is my patch that worked will (along with moving index.html).

<details>

```diff

Index: phettest/phettest.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/phettest/phettest.js b/phettest/phettest.js
--- a/phettest/phettest.js	(revision 5a2f4f399e6f62c5814a625bbc33c600178f6855)
+++ b/phettest/phettest.js	(date 1630766681654)
@@ -1,8 +1,8 @@
 // Copyright 2020, University of Colorado Boulder
 
 // will be replaced by domain name in the future
-const domain = 'https://bayes.colorado.edu/dev/';
-const serverURL = `${domain}phettest-server/`;
+const domain = 'http://localhost/main/';
+const serverURL = 'http://localhost:45362/'; // must end with /
 const phettestURL = `${domain}phettest/`;
 
 // common repo fields

```

</details>
