### ISSUE TITLE
Phetmarks combined launcher prototype

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/phetmarks#6]
Took a quick stab tonight at combining the best/desired features from phetmarks and the launcher, available at /phetmarks/testmarks.

It's designed to be keyboard-accessible and auto-complete simulation/wrapper names, along with providing custom categories for any repository. Should not need modification for the average sim added (unlike phetmarks), and should be easier to refactor in the future.

If this looks good, I can clean it up and document it (very rough under the hood).

**Comment by samreid** [comment]
I added some lint fixes, IIFE, etc above.

**Comment by samreid** [comment]
The above commit makes the main sim query string machine schema available to testmarks.  I tried populating the UI with elements and it worked OK except they were all checkboxes.  The next step would be to map flag => checkbox, boolean => checkbox, string => text box, etc.  After that, we could segregate the phet-io query parameters into a separate schema object, and make the simulation query strings available to testmarks by standardizing on a pattern (where they are located and how they are named), and by loading them through a requirejs bit.

**Comment by pixelzoom** [comment]
Comments on launcher:

1. Label the 2 columns, so we have common terminology. The first column is obviously "Repositories". The second column is what? "Tests"?

2. Most of what's in the second column is great big '?' for me. And I don't relish having to root reading source code to figure out what they are.  Could we get a description of each test by mousing over them?

3. Instead of a "Show Pointer Areas" check box, please provide a way to specify the query parameters, either in the URL or in a text field.  I don't want UI controls for each query parameter, and I don't want to have to add a UI control when I need to use a query parameter that's not supported. This is the #1 reason why I don't use phetmarks.

4. What is the Login button for? What is "your assigned ID number" and do I have one?

**Comment by pixelzoom** [comment]
Whoops... Looks like I'm testing the wrong thing, I should be testing testmarks.

**Comment by pixelzoom** [comment]
Feedback on testMarks:

1. The second column is a weird mix of tests and convenience function (GitHub, Issues). Recommended to remove "GitHub" and "Issues", and add a "GitHub" button next to "Launch". 

2. "Issues" is of questionable value, since you can get there with 1 click from "GitHub".

3. I'm guessing that "Compiled" is the same as "Built".  Why the new terminology?

4.  With "Require.js" and "Compiled", I see lots of UI controls (mostly check boxes) for query parameters. Please no... See 3 in https://github.com/phetsims/phetmarks/issues/6#issuecomment-261111418.

5. When I select "GitHub" or "Issues", I get a "Custom:" text field.  I'm guessing that this is for query parameters, since it has a "Reset Query Parameters" button below it.  Trying this feature, I'm stumped about what it does for me, since both of these "tests" take me to GitHub. Why isn't this field made available for launching sims? Ignoring that issue... Make the text field longer, label it "Query parameters:", label the button "Clear".

6. Keep the "common" entries (Require.js, Compiled, GitHub, Issues) at the top of the list.  When I switch to beers-law-lab, a bunch of additional entries were inserted after Compiled.

7. As noted in 2 of https://github.com/phetsims/phetmarks/issues/6#issuecomment-261111418, I think it's essential to be able to get a description of the entries in the second list (the things that you can launch).  Clicking on beers-law-lab (for example), I have no familiarity with most of the entries, whether they might be of use to me, etc.

**Comment by pixelzoom** [comment]
8. If a query parameter (e.g. fuzzMouse) is checked and included in the "Custom:" field, then QueryStringMachine fails with "Uncaught Error: Parameter supplied multiple times(…)"

**Comment by jonathanolson** [comment]
> (1) The second column is a weird mix of launchables and convenience functions (GitHub, Issues). Recommended to remove "GitHub" and "Issues", and add a "GitHub" button next to "Launch".

This would prevent the use case of:

1. Select a repository on the left (e.g. start typing, 'molecule-sha' => molecule-shapes).
2. Move to the next list (tab, currently two times), and select GitHub (e.g. by typing "git").
3. Hit enter to launch the intended URL (in this case, to GitHub).

Currently, launching a sim with require.js and launching its GitHub page are both just "open URL" actions, and it simplifies things to treat them that way (and allow very fast navigation).

> (2) "Issues" is of questionable value, since you can get there with 1 click from "GitHub".

True, but what is the cost of having this extra item? The argument applies to almost everything in phetmarks (unning a built sim is just typing "build/" and enter after loading the sim in require.js mode).

> (3) I'm guessing that "Compiled" is the same as "Built". Why the new terminology?

"built" is similar to "build", which would almost imply it would build the sim. Older phetmarks uses "build" which seems wrong, and I'd like to avoid the confusion (but don't care that much)

> Instead of a "Show Pointer Areas" check box, please provide a way to specify the query parameters, either in the URL or in a text field. ..., and I don't want to have to add a UI control when I need to use a query parameter that's not supported.

That's the "Custom" text input right beneath the query parameter UIs (whose name can be changed). Anything in that text box gets included in the query parameters. No need to add an UI control.

> I don't want UI controls for each query parameter

It is helpful for others (at least myself and SR), and by unchecking the two defaults ("brand=phet" and "ea") then you can just use the 'custom' field.

I personally never want to have to type ?ea&brand=phet (almost) every time I launch a sim in require.js mode.

> This is the #1 reason why I don't use phetmarks.

Understood. Would your ideal workflow for launching sims/wrappers/colors-pickers/etc. include something like testmarks/phetmarks? I'm open to adding features, but don't want to remove things that are useful for myself and others.

> (5) When I select "GitHub" or "Issues", I get a "Custom:" text field. I'm guessing that this is for query parameters, since it has a "Reset Query Parameters" button below it. Trying this feature, I'm stumped about why this is provided for "GitHub" and "Issues". But ignoring that... Make the text field longer, label it "Query parameters:", label the button "Clear".

We should hide that for things like GitHub where we don't care about adding query parameters. Improved label and length sounds good (there was a previous layout where it could go off of the screen if it was too long).

> (6) Keep the "common" entries (Require.js, Compiled, GitHub, Issues) at the top of the list. When I switch to beers-law-lab (for example), a bunch of additional entries are inserted after Compiled.

I'm more than fine with that order (I'll use github/issues more often than phet-io wrappers), but it would be good to get feedback on others if that order is fine. Agreed that common entries should be first.

> (7) As noted in 2 of #6 (comment), I think it's essential to be able to get a description of the launchables. Clicking on beers-law-lab (for example), I have no familiarity with most of the entries, whether they might be of use to me, etc.

I also don't know what most of the wrappers would be, and descriptions for everything sounds great.

I'll look into the following before the developer meeting:

1. Add descriptions for each column (repositories, "modes"? and query parameters)
2. Add descriptions for each mode (on hover)
3. Change "Custom:" to "Query parameters:" and increase the text box length.
4. Move GitHub and Issues in front of phet-io wrappers.

and will plan to discuss other points at the meeting.

**Comment by pixelzoom** [comment]
@jonathanolson Thanks for the clarification. 

I just wanted to point out that moving GitHub to a button wouldn't preclude fast navigation. It would just be a different navigation than what you described: select repo, tab a few times to GitHub button.

And you should definitely solicit input from developers who have been using phetmarks.  I don't use phetmarks, and I'm honestly unlikely to use this new tool (unless I have to deal with phet-io stuff).

**Comment by samreid** [comment]
I also prefer to leave "GitHub" in the list of "actions", so that it is keyboard navigable using the strategy @jonathanolson mentioned.

**Comment by pixelzoom** [comment]
> When you click a mode, the text box fills with the text?

If you mean text that describes the mode, then yes.

> Perhaps the 2nd column is "Actions"? i

Lauch is an action. Things in the 2nd column are the arguments for that action.

> we could leverage the QueryStringMachine schemas to automatically create a UI 

Sounds nontrivial.  Would you display only the query parameters in initialized-globals.js, or would you include sim-specific query parameters too?

**Comment by samreid** [comment]
Actions: "launch in **requirejs**", "open in **GitHub**", "show the GitHub **issues**", "launch with the **instance proxies** wrapper", "launch the **Compiled** version", etc.

>>  When you click a mode, the text box fills with the text?

> If you mean text that describes the mode, then yes.

Yes, the text that describes the action/mode.

> Would you display only the query parameters in initialized-globals.js, or would you include sim-specific query parameters too?

We would standardize on the location and naming of the sim specific query parameter schema, and include it.

**Comment by pixelzoom** [comment]
>  For instance: type: flag=> checkbox. type:'string' => text box, etc.

( type:'string' || type:'number' ) && validValues => combo box
type:'string' && !validValues => textfield
type:'number' && !validValues => spinner
initialize all of the above using defaultValues
...

Like I said... nontrivial.

**Comment by samreid** [comment]
Simpler:

validValues => radio buttons
flag => checkbox
boolean => checkbox
string => text area

That would get us pretty far.

**Comment by pixelzoom** [comment]
> Actions: "launch in requirejs", "open in GitHub", "show the GitHub issues", "launch with the instance proxies wrapper", "launch the Compiled version", etc.

All of these are `action preposition noun` or `action noun`, where action in all cases is `launch`.  I see no argument for labeling the second column "Actions".

**Comment by pixelzoom** [comment]
> Simpler:
> 
> validValues => radio buttons

How is using radio buttons for valid values simpler than using a check box? And it takes up way more real estate.

**Comment by samreid** [comment]
> All of these are `action preposition noun` or `action noun`, where action in all cases is `launch`.

Good point!  I'm fine with "modes" or the likes.

> How is using radio buttons for valid values simpler than using a check box? 

I suppose you meant combo box.  I'm fine with either one, but prefer the "see all of the options at once and be able to click them right away" nature of the radio buttons, at least for development tools.  I reserve the right to change my vote after seeing it look awkward.  If there are >4 radio buttons or so, we could fallback to combo box.

**Comment by pixelzoom** [comment]
It sounds like tab navigation is important to you. So keep in mind that using radio buttons will potentially require more tabs to get to the query parameter that you're interested in.  You'll need to tab past N radio buttons (where N is the number of valid values) versus 1 combo box.

**Comment by samreid** [comment]
> It sounds like tab navigation is important to you.

I'm interested in keyboard accessibility for the first two columns, being able to press "enter" to launch, and having it remember my settings.  I don't imagine tabbing through a lot of query parameters, I would use the mouse for that.

**Comment by jonathanolson** [comment]
Recommend changes:

1. Add descriptions for each column (repositories, "modes"? and query parameters)
2. Add descriptions for each mode (on hover)
3. Change "Custom:" to "Query parameters:" and increase the text box length.
4. Move GitHub and Issues in front of phet-io wrappers.
5. Add a 'screens' query parameter, but have radio buttons, with "all" and 6 screen-specific options.

**Comment by jonathanolson** [comment]
Resolved the above changes, and just pushed changes to replace the main 'phetmarks'.

Closing, will create issues for documentation and code improvement.
