### ISSUE TITLE
color editor could use an "export changed properties" feature

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#60]
From discussion with @ariel-phet around the process used in https://github.com/phetsims/build-a-nucleus/issues/83. It can be hard to find the changed colors and to get their values when editing many colors at once (as we did for the BAN Nuclide Chart).

**Comment by zepumph** [comment]
After the above commit, we can output changed colors in this format:

```
Changed Colors:
 buildANucleus.neutronEmissionColor: (164, 101, 164)
 buildANucleus.betaMinusColor: (148, 245, 245, 0)
 buildANucleus.alphaColor: (40, 215, 86, 0.25)
 buildANucleus.stableColor: (27, 20, 100, 0.3)
```

Note that if the alpha is `1`, it will be ignored in the RGB formatting. I did it like this because it is very easy to past the value in as the constructor for a `Color`, like `new Color(164, 101, 164)`.

@ariel-phet, anything else here?

**Comment by ariel-phet** [comment]
@zepumph, looks good and a couple of other people have used this feature now!
