### ISSUE TITLE
Color Editor: order colors by colorName

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#63]
Could we order the colors in Color Editor alphabetically, by the `colorName` arg to ProfileColorProperty?  They currently appear in the order that the ProfileColorProperty instances were instantiated.  For a sim with a large number of colors that have "guessable" names (like faradays-electromagnetic-lab), alphabetical ordering would improve usability.  And I shouldn't need to reorder my ProfileColorProperty instances (e.g. in FELColors.ts) to optimize usability.

I looks like @samreid has the most commits on color-editor.html, while @zepumph has the most recent commits. So I'll start by assigning to them.

**Comment by zepumph** [comment]
I'll take a look, thanks.

**Comment by zepumph** [comment]
Alrighty. Hows that? Is there any reason that we would want this to be optional? Like the location within the color profile is helpful organization?

**Comment by pixelzoom** [comment]
> Alrighty. Hows that?

Very nice, thanks!  And I suspect that @arouinfar will find this helpful when doing the color design for FEL in https://github.com/phetsims/faradays-electromagnetic-lab/issues/32.

> Is there any reason that we would want this to be optional? Like the location within the color profile is helpful organization?

I don't think there's any reason to make this optional.  Let's wait until someone asks.
