### ISSUE TITLE
Color Editor: Color dialog closes after single key press

### ISSUE THREAD

**Issue by arouinfar** [phetsims/phetmarks#64]
Steps to reproduce:
1. Open any sim color profile with the color editor on phetmarks. I discovered in faradays-electromagnetic-lab, but any sim should do.
2. Click on a color swatch to open the color dialog.
3. Start entering a value, the dialog will close after one key press.

This renders the color editor on phetmarks practically unusable. I'm using macOS/Chrome and @samreid was also able to reproduce on his machine (not sure what platform).

@zepumph volunteered to look into this issue, since he recently worked on the color editor in #63.

**Comment by zepumph** [comment]
Gross. I'll take a look now.

**Comment by zepumph** [comment]
Should be fixed now. Sorry about that!!

**Comment by arouinfar** [comment]
Thanks @zepumph! It's working nicely on main now, closing.
