### ISSUE TITLE
Query parameters can go off the screen

### ISSUE THREAD

**Issue by zepumph** [phetsims/phetmarks#65]
Noted today during dev meeting. I'm not sure how to fix this, but it seems like we should have a double scroll for sims and query parameters each. Thanks!

Devs don't seem too worried about it, but the whole team uses this via phettest, so medium-low priority?

![image](https://github.com/phetsims/phetmarks/assets/6856943/8c23bb15-4f6d-4329-808a-d83e5c2fcfd8)

**Comment by marlitas** [comment]
How pretty does this need to be? Is this good enough?

```diff
Subject: [PATCH] phetmarks css
---
Index: index.html
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/index.html b/index.html
--- a/index.html	(revision c0cb7d7d01ce1d8cbfa39f31c65300bbad254e4c)
+++ b/index.html	(date 1710806993692)
@@ -58,6 +58,10 @@
       left: 0;
       top: 10px;
       text-align: left;
+      overflow: scroll;
+      height: 90%;
+      width: 50%;
+      padding: 5px;
     }
 
     #choices select {
```

**Comment by zepumph** [comment]
Love it! 

* I liked 95% instead of 90% so we aren't wasting any space.
* I found https://stackoverflow.com/questions/18716863/css-hide-scroll-bar-if-not-needed that said `auto` will only show the scroll bar if needed.
* I felt like we only needed y scrolling, the x wraps.

Thanks for taking the lead on this.  Anything else here?

**Comment by marlitas** [comment]
I think this issue can be closed!
