### ISSUE TITLE
subdirectories in phetmarks? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/phetmarks#8]
What are these subdirectories in phetmarks?  There's no documentation.

phetmarks/launcher/
phetmarks/phettest/
phetmarks/testmarks/

A line or two about what these are for would be really nice. Reference associated GitHub issue, if there is one.

Assigning to @samreid and @jonathanolson, since you created these.

**Comment by samreid** [comment]
Where should this be documented?

Launcher looks like this and is poised to be replaced by testmarks:

![image](https://cloud.githubusercontent.com/assets/679486/20314782/974555c2-ab18-11e6-8c72-cdf93bf48c1d.png)

**Comment by pixelzoom** [comment]
This is like asking why NumberControl needs to be documented because you can see it on the screen when you run a sim. 

Document the source code.

**Comment by jonathanolson** [comment]
Added info to the top-level README. If we keep testmarks (or replace phetmarks' main index with it), I'll clean up and document it as noted in https://github.com/phetsims/phetmarks/issues/6. I just don't want to polish code that might get tossed.

**Comment by pixelzoom** [comment]
Thanks, but that's 2 out of 3.   No one has identified phettest.

**Comment by jonathanolson** [comment]
> Thanks, but that's 2 out of 3. No one has identified phettest.

Totally forgot that was in this repo! Documented in README.md now. I'm creating a separate 'document phettest' issue, as its documentation is lacking.

**Comment by samreid** [comment]
I removed the launcher subdirectory, it is superceded by phetmarks.  Other subdirectories are documented in README.md or their source code.
